<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";
import { ElMessage } from "element-plus";
import { Plus, RefreshRight } from "@element-plus/icons-vue";
import { qualityRiskApi } from "@/api/quality-risk.api";
import { useAuthStore } from "@/stores/auth.store";

const auth=useAuthStore(); const rows=ref<any[]>([]); const loading=ref(false); const dialog=ref(false);
const form=reactive({code:"RISK-GENERAL",name:"通用质量风险分级政策",version:"v1",rulesText:JSON.stringify({severity:{low:1,medium:2,high:3,critical:4},likelihood:{rare:1,possible:2,likely:3},exposure:{limited:1,regional:2,widespread:3},evidence_sufficiency:{minimum:0.8},level_mapping:{low:[1,2],medium:[3,4],high:[5,7],critical:[8,12]}},null,2)});
async function load(){loading.value=true;try{rows.value=(await qualityRiskApi.policies()).data.data;}finally{loading.value=false}}
async function save(){let rules;try{rules=JSON.parse(form.rulesText);}catch{ElMessage.warning("规则内容必须是JSON对象");return}await qualityRiskApi.createPolicy({code:form.code,name:form.name,version:form.version,rules});dialog.value=false;ElMessage.success("风险政策草稿已创建");await load()}
async function publish(row:any){await qualityRiskApi.publishPolicy(row.id);ElMessage.success("风险政策已发布");await load()}
onMounted(load);
</script>
<template><main class="policy-page"><header><div><p>RISK POLICY</p><h1>风险分级政策</h1><span>专家维护严重度、可能性、暴露范围和证据门槛；管理员发布后才可用于正式研判。</span></div><div><el-button :icon="RefreshRight" @click="load">刷新</el-button><el-button v-if="['admin','expert'].includes(auth.role)" type="primary" :icon="Plus" @click="dialog=true">新建版本</el-button></div></header><el-table :data="rows" v-loading="loading"><el-table-column prop="code" label="政策编码"/><el-table-column prop="name" label="名称"/><el-table-column prop="version" label="版本" width="90"/><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="row.status==='published'?'success':'info'">{{row.status==='published'?'已发布':'草稿'}}</el-tag></template></el-table-column><el-table-column width="100"><template #default="{row}"><el-button v-if="auth.role==='admin'&&row.status!=='published'" link @click="publish(row)">发布</el-button></template></el-table-column></el-table><el-dialog v-model="dialog" title="新建风险政策版本" width="min(720px,94vw)" top="5vh"><el-form label-position="top"><div class="grid"><el-form-item label="政策编码"><el-input v-model="form.code"/></el-form-item><el-form-item label="名称"><el-input v-model="form.name"/></el-form-item><el-form-item label="版本"><el-input v-model="form.version"/></el-form-item></div><el-form-item label="结构化规则"><el-input v-model="form.rulesText" type="textarea" :rows="16"/></el-form-item><el-alert type="info" :closable="false" title="风险概率仍需独立校准；政策只生成等级门槛，不能把模型自信度当概率。"/></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存草稿</el-button></template></el-dialog></main></template>
<style scoped>.policy-page{max-width:1280px;margin:0 auto;padding:24px}.policy-page>header{display:flex;align-items:flex-end;justify-content:space-between;gap:24px;margin-bottom:18px;padding:28px;border:1px solid #d8e5ec;border-radius:16px;background:linear-gradient(120deg,#f2f8fb,#fff)}header p{margin:0 0 8px;color:#b35b0b;font:700 11px ui-monospace,monospace;letter-spacing:.14em}h1{margin:0;font-size:34px}header span{display:block;margin-top:8px;color:#62798a}header>div:last-child{display:flex;gap:8px}.el-table{border:1px solid #dfe8ed;border-radius:14px}.grid{display:grid;grid-template-columns:1fr 1.5fr .7fr;gap:14px}@media(max-width:700px){.policy-page{padding:12px}.policy-page>header{align-items:flex-start;flex-direction:column;padding:20px 16px}.grid{grid-template-columns:1fr}}</style>
