from __future__ import annotations

from typing import Any


STANDARD_META_REGISTRY: dict[str, dict[str, Any]] = {
    "GB-T-3532-2022.pdf": {
        "standard_no": "GB/T 3532-2022",
        "standard_name": "日用瓷器",
        "domain": "日用陶瓷",
        "product_category": "日用瓷器",
        "standard_level": "GB/T",
        "standard_status": "现行",
        "inspection_items": ["外观质量", "缺陷判定", "规格要求"],
        "image_defect_keywords": ["裂纹", "缺釉", "斑点", "崩边", "变形", "色差"],
    },
    "GB+3532-2022.pdf": {
        "standard_no": "GB/T 3532-2022",
        "standard_name": "日用瓷器",
        "domain": "日用陶瓷",
        "product_category": "日用瓷器",
        "standard_level": "GB/T",
        "standard_status": "现行",
        "inspection_items": ["外观质量", "缺陷判定", "规格要求"],
        "image_defect_keywords": ["裂纹", "缺釉", "斑点", "崩边", "变形", "色差"],
    },
    "GB-T-3301-2023.pdf": {
        "standard_no": "GB/T 3301-2023",
        "standard_name": "日用陶瓷器规格误差和缺陷尺寸的测定方法",
        "domain": "日用陶瓷",
        "product_category": "日用陶瓷器",
        "standard_level": "GB/T",
        "standard_status": "现行",
        "inspection_items": ["缺陷尺寸", "规格误差", "外观缺陷测量"],
        "image_defect_keywords": ["缺陷尺寸", "裂纹", "斑点", "缺釉", "崩边"],
    },
    "GB+3301-2023.pdf": {
        "standard_no": "GB/T 3301-2023",
        "standard_name": "日用陶瓷器规格误差和缺陷尺寸的测定方法",
        "domain": "日用陶瓷",
        "product_category": "日用陶瓷器",
        "standard_level": "GB/T",
        "standard_status": "现行",
        "inspection_items": ["缺陷尺寸", "规格误差", "外观缺陷测量"],
        "image_defect_keywords": ["缺陷尺寸", "裂纹", "斑点", "缺釉", "崩边"],
    },
    "GB-T-3298-2022.pdf": {
        "standard_no": "GB/T 3298-2022",
        "standard_name": "日用陶瓷器抗热震性测定方法",
        "domain": "日用陶瓷",
        "product_category": "日用陶瓷器",
        "standard_level": "GB/T",
        "standard_status": "现行",
        "inspection_items": ["抗热震", "冷热冲击", "开裂判定"],
        "image_defect_keywords": ["裂纹", "开裂", "炸裂", "抗热震"],
    },
    "GB-T-5003-2023.pdf": {
        "standard_no": "GB/T 5003-2023",
        "standard_name": "日用陶瓷器釉面耐化学腐蚀性的测定方法",
        "domain": "日用陶瓷",
        "product_category": "日用陶瓷器",
        "standard_level": "GB/T",
        "standard_status": "现行",
        "inspection_items": ["釉面耐腐蚀", "表面质量"],
        "image_defect_keywords": ["釉面", "脱釉", "腐蚀", "表面质量"],
    },
    "GB-T-6544-2008.pdf": {
        "standard_no": "GB/T 6544-2008",
        "standard_name": "瓦楞纸板",
        "domain": "包装材料",
        "product_category": "瓦楞纸板",
        "standard_level": "GB/T",
        "standard_status": "现行",
        "inspection_items": ["纸板外观", "厚度", "耐破"],
        "image_defect_keywords": ["压痕", "破损", "纸板", "厚度", "耐破"],
    },
    "6544-2008-gbt-e-300.pdf": {
        "standard_no": "GB/T 6544-2008",
        "standard_name": "瓦楞纸板",
        "domain": "包装材料",
        "product_category": "瓦楞纸板",
        "standard_level": "GB/T",
        "standard_status": "现行",
        "inspection_items": ["纸板外观", "厚度", "耐破"],
        "image_defect_keywords": ["压痕", "破损", "纸板", "厚度", "耐破"],
    },
    "GB-T-7705-2008.pdf": {
        "standard_no": "GB/T 7705-2008",
        "standard_name": "平版装潢印刷品",
        "domain": "包装印刷",
        "product_category": "平版装潢印刷品",
        "standard_level": "GB/T",
        "standard_status": "现行",
        "inspection_items": ["印刷外观", "套印", "色差"],
        "image_defect_keywords": ["色差", "套印", "污点", "印刷偏移"],
    },
    "GB-T-7706-2008.pdf": {
        "standard_no": "GB/T 7706-2008",
        "standard_name": "凸版装潢印刷品",
        "domain": "包装印刷",
        "product_category": "凸版装潢印刷品",
        "standard_level": "GB/T",
        "standard_status": "现行",
        "inspection_items": ["印刷外观", "脏污", "色差"],
        "image_defect_keywords": ["色差", "脏污", "印刷缺陷", "套印"],
    },
    "GB-T-7707-2008.pdf": {
        "standard_no": "GB/T 7707-2008",
        "standard_name": "凹版装潢印刷品",
        "domain": "包装印刷",
        "product_category": "凹版装潢印刷品",
        "standard_level": "GB/T",
        "standard_status": "现行",
        "inspection_items": ["印刷外观", "墨色", "套印"],
        "image_defect_keywords": ["色差", "斑点", "墨色", "套印"],
    },
    "GB-18401-2010.pdf": {
        "standard_no": "GB 18401-2010",
        "standard_name": "国家纺织产品基本安全技术规范",
        "domain": "纺织服装",
        "product_category": "纺织产品",
        "standard_level": "GB",
        "standard_status": "现行",
        "inspection_items": ["安全类别", "异味", "色牢度", "甲醛", "pH"],
        "image_defect_keywords": ["异味", "色牢度", "安全类别", "标签"],
    },
    "GB-T-22848-2022.pdf": {
        "standard_no": "GB/T 22848-2022",
        "standard_name": "针织成品布",
        "domain": "纺织服装",
        "product_category": "针织成品布",
        "standard_level": "GB/T",
        "standard_status": "现行",
        "inspection_items": ["布面疵点", "色差", "织造缺陷"],
        "image_defect_keywords": ["布面疵点", "色差", "污渍", "织造缺陷"],
    },
    "GB-T-22849-2024.pdf": {
        "standard_no": "GB/T 22849-2024",
        "standard_name": "针织T恤衫",
        "domain": "纺织服装",
        "product_category": "针织T恤衫",
        "standard_level": "GB/T",
        "standard_status": "现行",
        "inspection_items": ["缝制", "规格", "外观疵点"],
        "image_defect_keywords": ["缝制", "线头", "色差", "外观疵点"],
    },
    "GB-T-2660-2017.pdf": {
        "standard_no": "GB/T 2660-2017",
        "standard_name": "衬衫",
        "domain": "纺织服装",
        "product_category": "衬衫",
        "standard_level": "GB/T",
        "standard_status": "现行",
        "inspection_items": ["缝制", "外观", "规格"],
        "image_defect_keywords": ["缝制", "线头", "色差", "污渍", "规格"],
    },
    "GB-T-29862-2013.pdf": {
        "standard_no": "GB/T 29862-2013",
        "standard_name": "纺织品 纤维含量的标识",
        "domain": "纺织服装",
        "product_category": "纺织标签",
        "standard_level": "GB/T",
        "standard_status": "现行",
        "inspection_items": ["标签", "成分", "纤维含量"],
        "image_defect_keywords": ["标签", "成分", "纤维含量", "标识"],
    },
    "29862-2013-gbt-e-300.pdf": {
        "standard_no": "GB/T 29862-2013",
        "standard_name": "纺织品 纤维含量的标识",
        "domain": "纺织服装",
        "product_category": "纺织标签",
        "standard_level": "GB/T",
        "standard_status": "现行",
        "inspection_items": ["标签", "成分", "纤维含量"],
        "image_defect_keywords": ["标签", "成分", "纤维含量", "标识"],
    },
    "GB-T-4893.4-2023.pdf": {
        "standard_no": "GB/T 4893.4-2023",
        "standard_name": "家具表面漆膜理化性能试验 第4部分：附着力交叉切割测定法",
        "domain": "家具木制品",
        "product_category": "家具表面",
        "standard_level": "GB/T",
        "standard_status": "现行",
        "inspection_items": ["漆膜", "附着力", "交叉切割"],
        "image_defect_keywords": ["漆膜", "脱落", "附着力", "划格"],
    },
    "GB-T-10357.5-2023.pdf": {
        "standard_no": "GB/T 10357.5-2023",
        "standard_name": "家具力学性能试验 第5部分：柜类强度和耐久性",
        "domain": "家具木制品",
        "product_category": "柜类家具",
        "standard_level": "GB/T",
        "standard_status": "现行",
        "inspection_items": ["强度", "耐久", "结构"],
        "image_defect_keywords": ["结构", "变形", "强度", "耐久"],
    },
    "GB-T-4822-2023.pdf": {
        "standard_no": "GB/T 4822-2023",
        "standard_name": "锯材检验",
        "domain": "家具木制品",
        "product_category": "锯材",
        "standard_level": "GB/T",
        "standard_status": "现行",
        "inspection_items": ["锯材检验", "木材缺陷"],
        "image_defect_keywords": ["裂纹", "节子", "腐朽", "木材缺陷"],
    },
    "GB-T-8170-2008.pdf": {
        "standard_no": "GB/T 8170-2008",
        "standard_name": "数值修约规则与极限数值的表示和判定",
        "domain": "通用质检",
        "product_category": "数值判定",
        "standard_level": "GB/T",
        "standard_status": "现行",
        "inspection_items": ["修约", "极限值", "判定"],
        "image_defect_keywords": ["修约", "极限值", "允许偏差", "判定"],
    },
}
