from __future__ import annotations

from typing import Any


DEFAULT_STRICT_PAPER_TEMPLATE_ID = "cqupt_graduate_thesis_2022"


PAPER_FORMAT_TEMPLATES: dict[str, dict[str, Any]] = {
    "generic_cn_thesis": {
        "template_id": "generic_cn_thesis",
        "name": "通用中文论文模板",
        "version": "v1",
        "description": "用于第一版论文查非功能的通用规则集。",
        "docx_rules": {
            "required_sections": ["摘要", "关键词", "参考文献"],
        },
        "tex_rules": {
            "required_commands": ["title", "author"],
            "required_sections": ["摘要", "参考文献"],
        },
    },
    "cqupt_graduate_thesis_2022": {
        "template_id": "cqupt_graduate_thesis_2022",
        "name": "重庆邮电大学研究生学位论文模板（2022版）",
        "version": "V2.0",
        "description": "基于重庆邮电大学研究生学位论文 Word 模板与写作指南的辅助查非规则。",
        "storage": {
            "bucket": "paper-templates",
            "files": [
                {
                    "role": "word_commented_template",
                    "file_name": "附件1-Word批注版-重庆邮电大学研究生学位论文模板（2022版）V2.0.docx",
                    "object_key": "cqupt/graduate-thesis/2022/word-commented-template.docx",
                    "content_type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                },
                {
                    "role": "writing_guide",
                    "file_name": "附件4-写作指南-重庆邮电大学研究生学位论文模板（2022版）V2.0.docx",
                    "object_key": "cqupt/graduate-thesis/2022/writing-guide.docx",
                    "content_type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                },
            ],
        },
        "docx_rules": {
            "required_sections": [
                {
                    "key": "originality_statement",
                    "label": "原创性声明",
                    "aliases": ["独创性声明", "原创性声明", "学位论文独创性声明"],
                    "severity": "medium",
                    "match_mode": "heading_or_text",
                },
                {
                    "key": "authorization_statement",
                    "label": "授权声明",
                    "aliases": ["使用授权书", "授权声明", "学位论文使用授权书"],
                    "severity": "medium",
                    "match_mode": "heading_or_text",
                },
                {
                    "key": "abstract",
                    "label": "摘要",
                    "aliases": ["摘要", "摘 要", "摘　要", "中文摘要"],
                    "severity": "high",
                    "match_mode": "heading_or_text",
                },
                {
                    "key": "keywords",
                    "label": "关键词",
                    "aliases": ["关键词", "关键字"],
                    "severity": "medium",
                    "match_mode": "heading_or_text",
                },
                {
                    "key": "en_abstract",
                    "label": "英文摘要",
                    "aliases": ["Abstract", "ABSTRACT"],
                    "severity": "high",
                    "match_mode": "heading_or_text",
                },
                {
                    "key": "en_keywords",
                    "label": "英文关键词",
                    "aliases": ["Keywords", "Key words"],
                    "severity": "medium",
                    "match_mode": "heading_or_text",
                },
                {
                    "key": "toc",
                    "label": "目录",
                    "aliases": ["目录", "目 录", "目　录"],
                    "severity": "medium",
                    "match_mode": "heading_or_text",
                },
                {
                    "key": "body",
                    "label": "正文",
                    "aliases": ["正文", "引言", "绪论", "研究内容", "实验结果", "总结与展望", "结论"],
                    "severity": "medium",
                    "match_mode": "body_between_sections",
                },
                {
                    "key": "references",
                    "label": "参考文献",
                    "aliases": ["参考文献", "References", "REFERENCES", "Bibliography"],
                    "severity": "high",
                    "match_mode": "heading_or_text",
                },
            ],
            "optional_sections": [
                {
                    "key": "figure_toc",
                    "label": "图目录",
                    "aliases": ["图目录"],
                    "severity": "low",
                    "match_mode": "heading_or_text",
                    "trigger": {"type": "min_figure_count", "value": 3},
                },
                {
                    "key": "table_toc",
                    "label": "表目录",
                    "aliases": ["表目录"],
                    "severity": "low",
                    "match_mode": "heading_or_text",
                    "trigger": {"type": "min_table_count", "value": 3},
                },
                {
                    "key": "notation_list",
                    "label": "主要符号表",
                    "aliases": ["主要符号表"],
                    "severity": "low",
                    "match_mode": "heading_or_text",
                    "trigger": {"type": "contains_any", "keywords": ["主要符号表"]},
                },
                {
                    "key": "abbreviation_list",
                    "label": "缩略词表",
                    "aliases": ["缩略词表"],
                    "severity": "low",
                    "match_mode": "heading_or_text",
                    "trigger": {"type": "contains_any", "keywords": ["缩略词表"]},
                },
                {
                    "key": "appendix",
                    "label": "附录",
                    "aliases": ["附录", "附录A", "附录 B"],
                    "severity": "low",
                    "match_mode": "heading_or_text",
                    "trigger": {"type": "contains_any", "keywords": ["附录"]},
                },
                {
                    "key": "author_profile",
                    "label": "作者简介",
                    "aliases": ["作者简介", "个人简历", "基本情况"],
                    "severity": "low",
                    "match_mode": "heading_or_text",
                    "trigger": {"type": "contains_any", "keywords": ["作者简介", "攻读学位期间的研究成果", "基本情况"]},
                },
                {
                    "key": "acknowledgements",
                    "label": "致谢",
                    "aliases": ["致谢", "致 谢", "致   谢", "致 謝"],
                    "severity": "low",
                    "match_mode": "heading_or_text",
                    "trigger": {"type": "contains_any", "keywords": ["致谢", "致 謝"]},
                },
            ],
            "section_alias_groups": {
                "摘要": ["摘要", "摘 要", "摘　要"],
                "ABSTRACT": ["ABSTRACT", "Abstract"],
                "目录": ["目录", "目 录", "目　录"],
                "图目录": ["图目录"],
                "表目录": ["表目录"],
                "主要符号表": ["主要符号表"],
                "缩略词表": ["缩略词表"],
                "参考文献": ["参考文献", "References", "REFERENCES", "Bibliography"],
                "附录": ["附录", "附录A", "附录 B"],
                "作者简介": ["作者简介", "个人简历", "基本情况"],
                "致谢": ["致谢", "致 谢", "致   谢", "致 謝"],
            },
            "section_order": [
                "原创性声明",
                "授权声明",
                "摘要",
                "关键词",
                "ABSTRACT",
                "Keywords",
                "目录",
                "图目录",
                "表目录",
                "正文",
                "参考文献",
                "附录",
                "作者简介",
                "致谢",
            ],
            "toc_required_entries": ["摘要", "ABSTRACT", "参考文献"],
            "page_size_cm": {"width": 21.0, "height": 29.7, "tolerance": 0.2},
            "page_orientation": "portrait",
            "page_margin_cm": {
                "top": 3.0,
                "bottom": 3.0,
                "left": 3.0,
                "right": 3.0,
                "tolerance": 0.2,
            },
            "gutter_cm": {"value": 0.0, "tolerance": 0.1},
            "header_footer": {
                "header_distance_cm": 2.0,
                "footer_distance_cm": 2.0,
                "tolerance": 0.2,
                "expected_header_patterns": [
                    "重庆邮电大学硕士学位论文",
                    "重庆邮电大学博士学位论文",
                    "重庆邮电大学专业学位硕士学位论文",
                    "重庆邮电大学专业学位博士学位论文",
                ],
                "expected_footer_pattern": "page_number_only",
                "cover_no_header_footer": True,
            },
            "abstract_keywords": {
                "min_count": 3,
                "max_count": 8,
                "separators": ["，", ",", "、"],
            },
            "body_font": {
                "zh": "宋体",
                "en": "Times New Roman",
                "size_pt": 12,
            },
            "line_spacing": 20.0,
            "style_match_tolerance": {
                "font_size_pt": 0.5,
                "line_spacing_pt": 1.0,
                "space_before_pt": 1.0,
                "space_after_pt": 1.0,
                "first_line_indent_pt": 2.0,
            },
            "front_matter_layout": {
                "abstract_heading": {
                    "aliases": ["摘要", "摘 要", "摘　要"],
                    "font_name": "黑体",
                    "font_size_pt": 16.0,
                    "bold": True,
                    "alignment": "center",
                    "line_spacing": 20.0,
                    "space_before_pt": 24.0,
                    "space_after_pt": 18.0,
                },
                "en_abstract_heading": {
                    "aliases": ["ABSTRACT", "Abstract"],
                    "font_name": "Times New Roman",
                    "font_size_pt": 16.0,
                    "bold": True,
                    "alignment": "center",
                    "line_spacing": 20.0,
                    "space_before_pt": 24.0,
                    "space_after_pt": 18.0,
                },
                "keywords_line": {
                    "aliases": ["关键词", "关键字"],
                    "font_name": "宋体",
                    "font_size_pt": 12.0,
                    "bold_prefix": True,
                    "alignment": "justify",
                    "line_spacing": 20.0,
                    "space_before_pt": 0.0,
                    "space_after_pt": 0.0,
                },
                "en_keywords_line": {
                    "aliases": ["Keywords", "Key words"],
                    "font_name": "Times New Roman",
                    "font_size_pt": 12.0,
                    "bold_prefix": True,
                    "alignment": "justify",
                    "line_spacing": 20.0,
                    "space_before_pt": 0.0,
                    "space_after_pt": 0.0,
                },
            },
            "heading_styles": {
                "level_1": {
                    "allowed_style_names": ["Heading 1"],
                    "numbering_patterns": [r"^第\d+章\s+", r"^\d+\s+"],
                    "font_name": "黑体",
                    "font_size_pt": 15.0,
                    "alignment": "center",
                    "line_spacing": 20.0,
                    "space_before_pt": 24.0,
                    "space_after_pt": 18.0,
                },
                "level_2": {
                    "allowed_style_names": ["Heading 2"],
                    "numbering_patterns": [r"^\d+\.\d+\s+"],
                    "font_name": "黑体",
                    "font_size_pt": 14.0,
                    "alignment": "left",
                    "line_spacing": 20.0,
                    "space_before_pt": 18.0,
                    "space_after_pt": 6.0,
                },
                "level_3": {
                    "allowed_style_names": ["Heading 3"],
                    "numbering_patterns": [r"^\d+\.\d+\.\d+\s+"],
                    "font_name": "黑体",
                    "font_size_pt": 14.0,
                    "alignment": "left",
                    "line_spacing": 20.0,
                    "space_before_pt": 12.0,
                    "space_after_pt": 6.0,
                },
                "level_4": {
                    "allowed_style_names": ["Heading 4"],
                    "numbering_patterns": [r"^\d+\.\d+\.\d+\.\d+\s+"],
                    "font_name": "黑体",
                    "font_size_pt": 12.0,
                    "alignment": "left",
                    "line_spacing": 20.0,
                    "space_before_pt": 12.0,
                    "space_after_pt": 6.0,
                },
            },
            "body_paragraph": {
                "zh_font": "宋体",
                "en_font": "Times New Roman",
                "font_size_pt": 12.0,
                "line_spacing": 20.0,
                "alignment": "justify",
                "space_before_pt": 0.0,
                "space_after_pt": 0.0,
                "first_line_indent_pt": 24.0,
            },
            "caption_styles": {
                "figure_cn": {
                    "match_prefixes": ["图"],
                    "allowed_style_names": ["中文图题", "多行中文图题"],
                    "font_name": "宋体",
                    "font_size_pt": 10.5,
                    "alignment": "center",
                    "line_spacing": 20.0,
                    "numbering_pattern": r"^图\d+(?:[-.]\d+)*",
                },
                "figure_en": {
                    "match_prefixes": ["Fig.", "Figure"],
                    "allowed_style_names": ["英文图题", "多行英文图题"],
                    "font_name": "Times New Roman",
                    "font_size_pt": 10.5,
                    "alignment": "center",
                    "line_spacing": 20.0,
                    "numbering_pattern": r"^(?:Fig\.|Figure)\s*\d+(?:[-.]\d+)*",
                },
                "table_cn": {
                    "match_prefixes": ["表"],
                    "allowed_style_names": ["中文表题", "多行表题"],
                    "font_name": "宋体",
                    "font_size_pt": 10.5,
                    "alignment": "center",
                    "line_spacing": 20.0,
                    "numbering_pattern": r"^表\d+(?:[-.]\d+)*",
                },
                "table_en": {
                    "match_prefixes": ["Table"],
                    "allowed_style_names": ["表题"],
                    "font_name": "Times New Roman",
                    "font_size_pt": 10.5,
                    "alignment": "center",
                    "line_spacing": 20.0,
                    "numbering_pattern": r"^Table\s*\d+(?:[-.]\d+)*",
                },
            },
            "page_numbering": {
                "front_matter": {"format": "roman", "alignment": "center"},
                "body": {"format": "arabic", "alignment": "center"},
            },
        },
        "pdf_rules": {
            "required_sections": ["摘要", "关键词", "目录", "参考文献"],
            "limitations": ["PDF 当前仅做文本抽取与结构辅助检查，不做严格版式比对。"],
        },
        "tex_rules": {
            "required_commands": ["title", "author"],
            "required_sections": ["摘要", "参考文献"],
        },
    },
}


def get_paper_template(template_id: str | None) -> dict[str, Any]:
    if template_id and template_id in PAPER_FORMAT_TEMPLATES:
        return PAPER_FORMAT_TEMPLATES[template_id]
    return PAPER_FORMAT_TEMPLATES["generic_cn_thesis"]
