import type { RoutingStrategyOverview } from "@/types/agent-ops.types";

export function buildFallbackRoutingStrategy(): RoutingStrategyOverview {
  return {
    route_mode: "router_enabled",
    default_target: "legacy_quality",
    root_graph: {
      selected_subgraph: "all",
      intent_name: "quality_root",
      agent_name: "QualityAgentRootGraph",
      nodes: [
        { id: "request_intake", label: "Request Intake", kind: "root" },
        { id: "route_signal_builder", label: "Route Signals", kind: "root" },
        { id: "route_policy", label: "Route Policy", kind: "root" },
        { id: "subgraph_runner", label: "Subgraph Runner", kind: "root" },
        { id: "contract_finalize", label: "Contract Finalize", kind: "root" },
        { id: "legacy_quality", label: "Legacy Quality", kind: "subgraph" },
        { id: "llm_native_quality", label: "LLM-native Quality", kind: "subgraph" },
      ],
      edges: [
        { source: "request_intake", target: "route_signal_builder" },
        { source: "route_signal_builder", target: "route_policy" },
        { source: "route_policy", target: "subgraph_runner" },
        { source: "subgraph_runner", target: "contract_finalize" },
        { source: "subgraph_runner", target: "legacy_quality" },
        { source: "subgraph_runner", target: "llm_native_quality" },
      ],
    },
    signals: [
      {
        key: "has_task_keyword",
        label: "任务意图关键词",
        description: "从用户文本中识别是否包含创建任务、提交任务、task 等任务流关键词。",
        source_stage: "route_signal_builder",
      },
      {
        key: "has_images",
        label: "图片附件",
        description: "请求中存在图片附件时，优先走 legacy 视觉和任务桥接链路。",
        source_stage: "route_signal_builder",
      },
      {
        key: "has_file_attachments",
        label: "文件附件",
        description: "非图片文件会参与新智能体的文件解析和结构化质检判断。",
        source_stage: "route_signal_builder",
      },
      {
        key: "request_kind",
        label: "请求类型",
        description: "用于区分普通 chat 文本和其他类型请求，作为文本类的兜底判断信号。",
        source_stage: "route_signal_builder",
      },
      {
        key: "needs_external_knowledge",
        label: "外部知识需求",
        description: "该信号影响后续知识路由与 RAG，不决定主图分流优先级。",
        source_stage: "route_signal_builder",
      },
    ],
    priority_rules: [
      {
        order: 1,
        when: "命中 has_task_keyword",
        target_subgraph: "legacy_quality",
        reason: "Task creation intent detected; route to legacy task flow",
        examples: ["创建任务", "新建任务", "提交任务", "task"],
        stop_on_match: true,
      },
      {
        order: 2,
        when: "未命中任务意图且检测到 has_images",
        target_subgraph: "legacy_quality",
        reason: "Image attachment detected; route to legacy vision workflow",
        examples: ["上传图片", "多张缺陷图", "图片附件检测"],
        stop_on_match: true,
      },
      {
        order: 3,
        when: "前两条未命中，且检测到 has_file_attachments 或 request_kind=chat",
        target_subgraph: "llm_native_quality",
        reason: "Text or non-image file detected; route to LLM-native quality flow",
        examples: ["文本问答", "txt/docx/xlsx/csv/json 文件", "非图片资料解析"],
        stop_on_match: true,
      },
    ],
    decision_cards: [
      {
        key: "task-intent",
        title: "任务意图优先",
        target_subgraph: "legacy_quality",
        reason: "Task creation intent detected; route to legacy task flow",
        priority_order: 1,
        matched_signals: ["has_task_keyword"],
        summary: "一旦命中文本任务关键词，直接进入 legacy_quality，后续条件不再继续参与判断。",
      },
      {
        key: "image-first",
        title: "图片走旧智能体",
        target_subgraph: "legacy_quality",
        reason: "Image attachment detected; route to legacy vision workflow",
        priority_order: 2,
        matched_signals: ["has_images"],
        summary: "图片输入优先进入 legacy_quality，兼容旧任务流和图片自动回填逻辑。",
      },
      {
        key: "text-file-native",
        title: "文本与非图片文件走新智能体",
        target_subgraph: "llm_native_quality",
        reason: "Text or non-image file detected; route to LLM-native quality flow",
        priority_order: 3,
        matched_signals: ["has_file_attachments", "request_kind"],
        summary: "文本和非图片文件进入 llm_native_quality，执行文件解析、推断、RAG 与结构化质检。",
      },
    ],
    subgraphs: [
      {
        subgraph_key: "legacy_quality",
        label: "Legacy Quality",
        summary: "旧智能体负责图片与任务流兼容处理。",
        entry_node: "legacy_quality.input_adapter",
        nodes: [
          { id: "legacy_quality", label: "Legacy Quality", kind: "subgraph" },
          { id: "legacy_quality.input_adapter", label: "Input Adapter", kind: "legacy" },
          { id: "legacy_quality.history_loader", label: "History Loader", kind: "legacy" },
          { id: "legacy_quality.planner", label: "Planner", kind: "legacy" },
          { id: "legacy_quality.task_extractor", label: "Task Extractor", kind: "legacy" },
          { id: "legacy_quality.knowledge", label: "Knowledge", kind: "legacy" },
          { id: "legacy_quality.reasoning", label: "Reasoning", kind: "legacy" },
          { id: "legacy_quality.quality_gate", label: "Quality Gate", kind: "legacy" },
          { id: "legacy_quality.task_executor", label: "Task Executor", kind: "legacy" },
          { id: "legacy_quality.response_writer", label: "Response Writer", kind: "legacy" },
          { id: "legacy_quality.finalizer", label: "Finalizer", kind: "legacy" },
        ],
        edges: [
          { source: "legacy_quality", target: "legacy_quality.input_adapter" },
          { source: "legacy_quality.input_adapter", target: "legacy_quality.history_loader" },
          { source: "legacy_quality.history_loader", target: "legacy_quality.planner" },
          { source: "legacy_quality.planner", target: "legacy_quality.task_extractor" },
          { source: "legacy_quality.task_extractor", target: "legacy_quality.knowledge" },
          { source: "legacy_quality.knowledge", target: "legacy_quality.reasoning" },
          { source: "legacy_quality.reasoning", target: "legacy_quality.quality_gate" },
          { source: "legacy_quality.quality_gate", target: "legacy_quality.task_executor" },
          { source: "legacy_quality.task_executor", target: "legacy_quality.response_writer" },
          { source: "legacy_quality.response_writer", target: "legacy_quality.finalizer" },
        ],
        typical_scenarios: [
          "消息命中创建任务、提交任务、task 等任务流关键词",
          "本轮输入包含图片附件，需要进入旧视觉工作流",
        ],
      },
      {
        subgraph_key: "llm_native_quality",
        label: "LLM-native Quality",
        summary: "新智能体负责文本与非图片文件驱动的解析、推断和质检物化。",
        entry_node: "llm_native_quality.intake_normalizer",
        nodes: [
          { id: "llm_native_quality", label: "LLM-native Quality", kind: "subgraph" },
          { id: "llm_native_quality.intake_normalizer", label: "Intake Normalizer", kind: "native" },
          { id: "llm_native_quality.file_loader", label: "File Loader", kind: "native" },
          { id: "llm_native_quality.contract_inferencer", label: "Contract Inferencer", kind: "native" },
          { id: "llm_native_quality.planner", label: "Planner", kind: "native" },
          { id: "llm_native_quality.knowledge_router", label: "Knowledge Router", kind: "native" },
          { id: "llm_native_quality.tool_loop", label: "Tool Loop", kind: "native" },
          { id: "llm_native_quality.evidence_synthesizer", label: "Evidence Synthesizer", kind: "native" },
          { id: "llm_native_quality.contract_mapper", label: "Contract Mapper", kind: "native" },
          { id: "llm_native_quality.review_gate", label: "Review Gate", kind: "native" },
          { id: "llm_native_quality.persist_emit", label: "Persist Emit", kind: "native" },
        ],
        edges: [
          { source: "llm_native_quality", target: "llm_native_quality.intake_normalizer" },
          { source: "llm_native_quality.intake_normalizer", target: "llm_native_quality.file_loader" },
          { source: "llm_native_quality.file_loader", target: "llm_native_quality.contract_inferencer" },
          { source: "llm_native_quality.contract_inferencer", target: "llm_native_quality.planner" },
          { source: "llm_native_quality.planner", target: "llm_native_quality.knowledge_router" },
          { source: "llm_native_quality.knowledge_router", target: "llm_native_quality.tool_loop" },
          { source: "llm_native_quality.tool_loop", target: "llm_native_quality.evidence_synthesizer" },
          { source: "llm_native_quality.evidence_synthesizer", target: "llm_native_quality.contract_mapper" },
          { source: "llm_native_quality.contract_mapper", target: "llm_native_quality.review_gate" },
          { source: "llm_native_quality.review_gate", target: "llm_native_quality.persist_emit" },
        ],
        typical_scenarios: [
          "用户发送纯文本问答，不涉及创建任务",
          "用户上传 txt、docx、xlsx、csv、json 等非图片文件进行质检",
        ],
      },
    ],
    registered_route_count: 0,
    registered_intents: [],
  };
}
